name: Build and Push Docker image
on:
  push:
  pull_request:

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    env:
      IMG_NAME: dev-iac

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3
  
    - name: Docker Hub Login
      id: docker-login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Specifies whether the given registry is ECR (auto, true or false)
        ecr: auto
        logout: true

    - name: Docker Metadata action
      id: docker-metadata
      uses: docker/metadata-action@v5.0.0
      with:
        # Where to get context data. Allowed options are "workflow"  (default), "git".
        #context: # default is workflow
        # List of Docker images to use as base name for tags
        images: ${{ env.IMG_NAME }}
        # List of tags as key-value pair attributes
        tags: latest # optional
        # Flavors to apply
        #flavor: # optional
        # List of custom labels
        labels: iac # optional
        # Separator to use for tags output (default \n)
        #sep-tags: # optional
        # Separator to use for labels output (default \n)
        #sep-labels: # optional
        # Bake target name (default docker-metadata-action)
        #bake-target: # optional
    
    - name: Build and push Docker image
      id: docker-build-push
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        labels: ${{ steps.metadata.outputs.labels }}
        no-cache: true
        outputs: docker.io/jasonouellet/dev-iac
        push: true
        sbom: true
        tags: ${{ steps.metadata.outputs.tags }}
