name: Build and Push Docker image
on:
  push:
  pull_request:

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    env:
      IMG_NAME: jasonouellet/dev-iac

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      id: setup-buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Hub Login
      id: docker-login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        ecr: auto
        logout: true

    - name: Docker Metadata action
      id: docker-metadata
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMG_NAME }}
        tags: latest
        labels: iac

    - name: Build and push Docker image
      id: docker-build-push
      uses: docker/build-push-action@v6
      with:
        context: .
        labels: ${{ steps.docker-metadata.outputs.labels }}
        no-cache: true
        push: true
        sbom: true
        tags: ${{ steps.docker-metadata.outputs.tags }}
